#!/bin/bash

# Check if the file parameter is provided
if [ -z "$1" ]; then
    echo "Usage: $0 <file>"
    exit 1
fi

# Get the file from the first argument
file="$1"

# Check if the file exists
if [ ! -f "$file" ]; then
    echo "File not found: $file"
    exit 1
fi

./analyzer/run < "$file"
python3 analyzer/postpro.py analyzer/.intermediate.lua
python3 interpreter/main.py analyzer/.intermediate.lua
rm analyzer/.intermediate.lua
